name: 'OpenAPI Custom Validator'
description: 'Validates an OpenAPI 3.0.x JSON spec using custom rules'
author: 'Jakub Filo'
inputs:
  spec-path:
    description: 'Path to OpenAPI JSON file in the caller repository'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Set up Java
    uses: actions/setup-java@v4
    with:
      distribution: corretto
      java-version: '25'
      cache: maven

  - name: Build validator jar
    working-directory: ${{ github.action_path }}
    shell: bash
    run: ./mvnw -B -DskipTests package

  - name: Run OpenAPI validator
    shell: bash
    run: |
      java -jar "${{ github.action_path }}/target/openapi-custom-validator-1.0.0-shaded.jar" \
        "${{ inputs.spec-path }}"
